### ISSUE TITLE
cannot intercept https traffic

### ISSUE THREAD

**Issue by masterkain** [APKLab/APKLab#120] opened 2021-02-17 00:32 UTC
hello,
as an exercise I wanted to try checking out the https traffic from this apk: https://apkcombo.com/it-it/wenano/com.tipanano.WeNanoLight/download/apk

I followed all the steps and everything is ok -- I can adb the app onto an android device and start it up.
I'm using Proxyman to intercept https traffic, device is configured properly (trusted cert, proxy settings).

However I still see handshake failures (app uses firebase I guess) and cannot proceed beyond the first screen.

```
--------------------------------------------
Applying patches for HTTPS inspection (MITM)
--------------------------------------------
Using apk-mitm v0.11.1 (https://github.com/shroudedcode/apk-mitm)

[1/3] Modifying app manifest
[2/3] Replacing network security config
[3/3] Disabling certificate pinning
Scanning Smali files...
okhttp3/CertificatePinner: Applied CertificatePinner#check (OkHttp 3.x) patch
com/squareup/okhttp/CertificatePinner: Applied HostnameVerifier#check (OkHttp 2.5) patch
okhttp3/internal/tls/OkHostnameVerifier: Applied HostnameVerifier#verify (javax) patch
io/grpc/okhttp/internal/OkHostnameVerifier: Applied HostnameVerifier#verify (javax) patch
com/squareup/okhttp/internal/tls/OkHostnameVerifier: Applied HostnameVerifier#verify (javax) patch

Successfully applied MITM patches!
```

should I ask @shroudedcode about this? thanks for the tool!

**Comment by Surendrajat** [comment] 2021-02-17 08:30
@masterkain You can also put those handshake failure errors here. Seems like some custom pinning method to me, but I'll not be able to test this out till weekend.
Let's wait for @shroudedcode to have a look at it. If it's indeed a new kind of pinning method then it'll require an update on `apk-mitm` side.

**Comment by shroudedcode** [comment] 2021-06-26 18:09
Sorry for the very late reply, but this issue kind of flew under my radar. 😅 Just in case this is still relevant, please open an issue over on [the `apk-mitm` repo](https://github.com/shroudedcode/apk-mitm) with runtime logs from the app (I recommend using [`pidcat`](https://github.com/JakeWharton/pidcat) for getting them).

@Surendrajat I think you can close this issue as it's definitely not caused by APKLab itself.

**Comment by Surendrajat** [comment] 2021-06-28 02:36
Thanks, @shroudedcode.

**Closed by Surendrajat** 2021-06-28 02:36 UTC
Labels: mitm
