### ISSUE TITLE
Running APKLab in offline environment (Open APK)

### ISSUE THREAD

**Issue by WeeslaX** [APKLab/APKLab#192] opened 2023-07-13 06:42 UTC
**Describe the bug**
When I try to run APKLab Open APK function in an offline machine, the extension does not show any output in console

**To Reproduce**

1. Download APKLab to VS Code portable
2. Run Portable VS Code in offline machine
3. Run "Open APK" command

**Expected behavior**
Program displays file explore

**Console Logs**
None

Please paste all your console output here... between the details HTML tags!

**System Information:**

- OS: Windows 10
- VSCode Version: Portable VSCode-win32-x64-1.80.0

**Additional context**
None

**Comment by Surendrajat** [comment] 2023-07-23 04:38
You need to run it at least once when you're online because APKLab downloads it's dependencies (Jadx, apktool, etc.). However you can disable `Apklab: Update Tools` setting to disable further update checks.
Duplicate of #190

**Comment by WeeslaX** [comment] 2023-07-24 13:31
Actually, I have initially got things to work on my offline environment after using a workaround but it returned to not opening the file explorer (and no output in the console) after a few days (even with "Further Update Checks" disabled).

I noticed on the other post that a new version was pushed down that will fix this issue. Will verify on my environment and let you know again.

Appreciate the response and help, @Surendrajat !

**Closed** 2023-09-04 16:49 UTC
Labels: duplicate
